openapi: 3.0.0
info:
  description: Gallery API
  version: 0.1-oas3
  title: Gallery API
servers:
  - url: http://127.0.0.1:3000
paths:
  /upload:
    post:
      responses:
        '200':
          description: Upload images to the server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Upload'
  /gallery:
    get:
      parameters:
        - name: page
          in: query
          required: false
          example: '1'
          schema:
            type: string
      responses:
        '200':
          description: Get images from the server
          content:
            '*/*':
              schema:
                type: string
  /:
    get:
      responses:
        '200':
          description: Get the gallery.html page
          content:
            text/html:
              schema:
                type: string
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        x-examples:
          application/json: |-
            {
                "email": "",
                "password": ""
            }
      responses:
        '200':
          description: Get the auth token from the server
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Login:
      properties:
        email:
          type: string
        password:
          type: string
    Upload:
      properties:
        error:
          type: string